version: "3.5"

services:
    cg_mongo:
        image: mongo
        restart: unless-stopped
        container_name: cg_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${CG_MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${CG_MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${CG_MONGO_USER}
        volumes:
            - cg_mongo:/data/db
        ports:
            - "${CG_MONGO_PORT}:27017"
        networks:
            - storage
networks:
    storage:
        driver: bridge
volumes:
    cg_mongo:
