version: "3.5"

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: ${HEROKU_PG_CG_USER}
            POSTGRES_DB: ${HEROKU_PG_CG_USER} # same as user
            POSTGRES_PASSWORD: ${HEROKU_PG_CG_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
