version: "3.5"

services:
    postgres_cga:
        container_name: postgres_container_cga
        image: postgres
        environment:
            POSTGRES_USER: ${PG_CGA_USER}
            POSTGRES_DB: ${PG_CGA_USER} # same as user
            POSTGRES_PASSWORD: ${PG_CGA_PASSWORD}
            PGDATA: /data/postgres_cga
        volumes:
            - postgres_cga:/data/postgres_cga
        ports:
            - "${PG_CGA_PORT}:5432"
        networks:
            - postgres
        restart: unless-stopped
    postgres_cgl:
        container_name: postgres_container_cgl
        image: postgres
        environment:
            POSTGRES_USER: ${PG_CGL_USER}
            POSTGRES_DB: ${PG_CGL_USER} # same as user
            POSTGRES_PASSWORD: ${PG_CGL_PASSWORD}
            PGDATA: /data/postgres_cgl
        volumes:
            - postgres_cgl:/data/postgres_cgl
        ports:
            - "${PG_CGL_PORT}:5432"
        networks:
            - postgres
        restart: unless-stopped
networks:
    postgres:
        driver: bridge
volumes:
    postgres_cga:
    postgres_cgl:
