import { extractRight } from "@shared/util-fp";
import {
  createSchemaFromClass,
  Data,
  NonEmptyProperty,
  RequiredArrayRef,
  RequiredObjectRef,
  RequiredStringArrayOf
} from "@shared/util-schema";
import * as g from "graphql";
import { toGraphQLType } from "./converters";

const info = {
    namespace: "test",
    name: "User",
    version: "v1",
};

class Comment {
    @NonEmptyProperty()
    text: string;
}

class City {
    @NonEmptyProperty()
    name: string;
}

class Address {
    @NonEmptyProperty()
    address: string;
    @RequiredObjectRef(City)
    city: City;
}

@Data({
    info,
})
class User {
    @NonEmptyProperty()
    id: string;
    @NonEmptyProperty()
    name?: string;
    @RequiredArrayRef(Comment)
    comments: Comment[];
    @RequiredStringArrayOf()
    skills: string[];
    @RequiredObjectRef(Address)
    address: Address;
}

const expectedSDL = `type User {
  """The unique identifier for this object generated by Content Gateway"""
  _id: ID!
  id: String
  name: String
  comments: [Comment]
  skills: [String]
  address: Address
}

type Comment {
  """The unique identifier for this object generated by Content Gateway"""
  _id: ID!
  text: String
}

type Address {
  """The unique identifier for this object generated by Content Gateway"""
  _id: ID!
  address: String
  city: City
}

type City {
  """The unique identifier for this object generated by Content Gateway"""
  _id: ID!
  name: String
}
`;

describe("Given a JSON schema type", () => {
    const schema = extractRight(createSchemaFromClass(User));

    describe("when converting it to a GraphQL schema", () => {
        const types = toGraphQLType(schema);

        it("then it is successfully converted", () => {
            const sdl = g.printSchema(new g.GraphQLSchema({ types: [types] }));
            expect(sdl).toEqual(expectedSDL);
        });
    });
});
