#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Builds the production version of the specified project."
    echo ""
    echo "Usage: ./build <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
fi

cd ..

nx build ${project_names[$1]} --prod
