#!/bin/bash

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Pushes your local state to the specified remote"
    echo ""
    echo "Usage: ./heroku-up <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Remote is missing!"
fi

git push $1
