#!/bin/bash

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Shows the Heroku logs for the given project"
    echo ""
    echo "Usage: ./heroku-log <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project is missing!"
fi

heroku logs --remote $1 --tail
