#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Generates the Prisma client for the specified project"
    echo ""
    echo "Usage: ./prisma-generate <project>"
    echo "Supported projects: cga, cgl"
    echo "Also supports the nx project names (for Heroku compatibility)."
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
    exit 1
fi

cd ..

project_name=${project_names[$1]}

if [ -z "$project_name" ]; then
    project_name=$1
fi

pushd apps/$project_name

echo "workdir is: $(pwd)"

npx prisma generate
popd
