#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Creates a new Prisma migration"
    echo ""
    echo "Usage: ./prisma-migrate <project> <migration-file-name>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
    exit 1
fi

if [ -z "$2" ]; then
    print_usage "Migration file name is missing!"
    exit 1
fi

cd ..

pushd ${projects[$1]}

workdir=$(pwd)

echo "Workdir is: $workdir"

npx prisma migrate dev --name $2

popd
