#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Runs Prisma studio for the given project"
    echo ""
    echo "Usage: ./prisma-studio <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "project is missing!"
fi

cd ..

pushd ${projects[$1]}

workdir=$(pwd)

echo "Workdir is: $workdir"

npx prisma studio

popd
