#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Migrates the local environment"
    echo ""
    echo "Usage: ./prisma-migrate-dev <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
    exit 1
fi

cd ..

pushd ${projects[$1]}

workdir=$(pwd)

echo "Workdir is: $workdir"

npx prisma migrate dev

popd
