#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Deploys the outstanding Prisma migrations"
    echo ""
    echo "Usage: ./prisma-deploy <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
fi

cd ..

pushd ${projects[$1]}

workdir=$(pwd)
echo "Workdir is: $workdir"

npx prisma generate
npx prisma migrate deploy

popd
