#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Serves a development version with hot code replace of the given project"
    echo ""
    echo "Usage: ./serve <project>"
    echo "Supported projects: cga, cgl"
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
fi

cd ..

nx serve ${project_names[$1]}
